# Generated by Django 5.2.6 on 2025-10-23 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_problema_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
