# Generated by Django 5.2.6 on 2025-12-11 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_problema_data_criacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='conteudo',
            new_name='texto',
        ),
        migrations.AddField(
            model_name='ideia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='ideias/'),
        ),
        migrations.AddField(
            model_name='problema',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='problemas/'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='ideia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_set', to='app.ideia'),
        ),
    ]
