# Generated by Django 5.2.6 on 2025-12-11 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_conteudo_comentario_texto_ideia_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='ideia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.ideia'),
        ),
    ]
